server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth
    username: root
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ture
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: debug